In [1]:
import pandas as pd

df = pd.read_csv('df_gui_1.csv') #dummy_data_gui.xlsx

In [2]:
import numpy as np
df['hotness']= np.where(df['song_year_y'] == 2010, df['song_hotness_y'],df['song_hotness_x'])
df.sort_values(by=['hotness'], ascending=False).head(10)

,Unnamed: 0,features,song_hotness_x,song_id,song_title_x,song_year_x,prediction,song_hotness_y,song_title_y,song_year_y,hotness
5574,5574,"[-963.1599999999997,4722.365000000002,-969.177...",1.082503,SOERTOA12A81C204F3,Big Brother,2007,4,NaN,NaN,NaN,1.082503
16816,16816,"[-280.11400000000015,4817.225000000001,787.892...",1.082503,SOPRFDU12A6D4FA254,School Spirit,2004,4,NaN,NaN,NaN,1.082503
14970,14970,"[416.797,4718.883,2470.9059999999995,-1924.975...",1.082503,SOPJXQA12A6701D925,All Falls Down,2005,8,NaN,NaN,NaN,1.082503
13943,13943,"[-311.3929999999999,5168.772000000001,231.1210...",1.082503,SOXJBVH12A8C1416CF,Diamonds From Sierra Leone,2005,4,NaN,NaN,NaN,1.082503
5417,5417,"[-491.08000000000004,4944.530999999999,1388.90...",1.082503,SOJBLDU12A8C1442B2,Diamonds From Sierra Leone,2005,4,NaN,NaN,NaN,1.082503
16797,16797,"[630.978,4712.998,5367.098999999999,-2407.0289...",1.082503,SOFRVNS12A6701D924,We Dont Care,2004,8,NaN,NaN,NaN,1.082503
172,172,"[-344.32599999999996,4875.958999999998,7621.31...",1.021256,SONZUTP12AF72AACC9,Superhereos,2001,11,NaN,NaN,NaN,1.021256
15417,15417,"[-1151.1199999999997,4786.305,5833.71600000000...",1.021256,SOVOOSP12A6310F1AC,Aerodynamic (Daft Punk Remix),2003,11,NaN,NaN,NaN,1.021256
7323,7323,"[1023.8150000000003,4391.914000000002,2065.375...",1.021256,SOSOHJD12A6D4F6664,Human After All (Emperor Machine Version ),2005,12,NaN,NaN,NaN,1.021256
815,815,"[793.567,5253.014000000001,7943.939000000003,3...",1.021256,SOWEBRA12A6701F115,Human After All,2005,3,NaN,NaN,NaN,1.021256

In [7]:
def return_song():
    input_string = input('Enter Song Title:')  
    indexer=df[df['song_title_x']==input_string].index
    cluster_num = df.loc[indexer,'prediction']
    cluster_list = df[df['prediction']==cluster_num.values.item(0)].sort_values(by=['hotness'], ascending=False).head(10)
    print(cluster_list['song_title_x'])
    
return_song()

Enter Song Title: Love Story

14970                                       All Falls Down
16797                                         We Dont Care
8078                                   Dont Stop The Music
3286                                            Take A Bow
6603                                   Dont Stop The Music
8626     Dead And Gone [feat. Justin Timerlake] (Explic...
11926                                           Sweet Lies
16795                                     Marshall Mathers
10091                                             LoveGame
12478                                               Closer
Name: song_title_x, dtype: object

## GUI Interface

In [3]:
from tkinter import *

window = Tk()

window.title("Song Recommonder")
window.geometry('500x500')

lbl = Label(window, text="    Welcome to Nostalgic Songs    ", font=("Gilbert Color Bold", 36))

lbl.grid(column=1, row=0)

txt = Entry(window,width=30)
txt.grid(column=1, row=1, pady=10)

songs = ("         All Falls Down",\
         "         We Don't Care",\
         "   Don't Stop the Music",\
         "          Take A Bow",\
         "        Dead And Gone",\
         "           Sweet Lies",\
         "      Marshall Mathers",\
         "            Love Game")

list1 = StringVar(value = songs)

def clicked():
    lbl1 = Label(window, text="   Your Playlist   ", font=("Gilbert Bold", 20))
    lbl1.grid(column=1, row=3, pady=20)
    listbox1 = Listbox(window, height=len(songs), listvariable=list1, selectmode="browse", font=("Felt Tip Roman", 18))
    listbox1.grid(column=1, row=4)


btn = Button(window, text = 'Explore', font=("Gilbert Color Bold", 24), command = clicked)
btn.grid(column=1, row=2)

window.mainloop()